### ISSUE TITLE
Indefinite "connecting" state on Windows 8.1

### ISSUE THREAD

**Issue by swstack** [adafruit/adafruit-bluefruit-le-desktop#17]
I have the app running on a Windows 8.1 VM (via Parallels Desktop) and it opens and scans for devices just fine.  However, when I click on a device to initiate the connection process it hangs indefinitely until I cancel it...

![screen shot 2015-10-15 at 4 17 23 pm](https://cloud.githubusercontent.com/assets/4336976/10527875/81d4c5e0-7358-11e5-92ef-f6ab6089ab53.png)

Has anyone seen similar behavior? Any additional info is greatly appreciated.

I plan on further debugging the issue by:

* Getting my hands on a native Windows machine (no VM)
* Running the app from source via the `electron` command directly

**Comment by swstack** [comment]
Well I think I may have spoke too soon ... I reset everything (VM and app) and it is now working... :+1:

**Comment by tdicola** [comment]
Oh no problem, thanks for raising the issue and following up with what fixed it for you.  Thanks!

**Comment by 0dividedby0** [comment]
Unfortunately, I am still having this problem on Windows 10. I have restarted my computer and the application more than once but still no luck. I noticed that in the Device Manager, the CSR8510 dongle is called "Generic Bluetooth Radio". I am trying to communicate with a LightBlue Bean via BLE and would appreciate any suggestions. Thanks

**Comment by codeblack67** [comment]
I also have this issue, both on a Windows 10 computer and a Windows 8.  The Zadig driver converter worked fine for me; on either computer I used, the bluetooth adaptor either showed up as CSR8510 or "Generic Bluetooth Radio", but had no issues converting the driver or recognizing my Bluefruit Feather when the app was opened on my computer.  The Feather just won't fully connect to the computer, and I can't figure out why.

**Comment by 0dividedby0** [comment]
Turns out I spoke too soon as well. After a lot of messing around, I found out that if you stop the scan after the device has been discovered but before you try to connect, it connects just fine. So to recap, scan until you see your device, stop the scan, then click on your device to connect. codeblack67, hope this works for you too.

**Comment by codeblack67** [comment]
0dividedby0, good work!  This fixed my issue.  Thanks!
