### ISSUE TITLE
MAC OSX Yosemite not connecting to Bluefruit EZ Link device

### ISSUE THREAD

**Issue by rMartin76** [adafruit/adafruit-bluefruit-le-desktop#23]
Having trouble in connecting the desktop app to the Bluefruit EZ Link module. Have everything hooked up correctly as I can communicate with the Arduino Sketch app. The status bar hangs at about 1/3 of the way.

**Comment by ladyada** [comment]
EZ link != Bluetooth LE
Tech support is handled in the forums, not github thanx!

**Comment by rMartin76** [comment]
Does that mean they are not compatible? Sorry, I bought a bluetooth module in the hopes of using the app and I'm just trying to figure out if I need to get a different one.

Thank you! This will be my last post to Github.
